---
    - hosts: all
      become: true
      vars_files:
        - vars/default.yml
    
      tasks:
        - name: Install aptitude using apt
          apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
    
        - name: Install required system packages
          apt: name={{ item }} state=latest update_cache=yes
          loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
    
        - name: Add Docker GPG apt Key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
    
        - name: Add Docker Repository
          apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu bionic stable
            state: present
    
        - name: Update apt and install docker-ce
          apt: update_cache=yes name=docker-ce state=latest
        
        - name: Install pip
          apt:
            name: python-pip
            update_cache: yes
            state: present
    
        - name: Install Docker Module for Python
          pip:
            name: docker
    
        - name: Docker Stop
          shell: docker stop $(docker ps -aq)
          become: true
          become: root
        
        - name: Docker pull 
          shell: docker pull avsek12/trcweb 
        
        - name: Docker remove container
          shell: docker rm $(docker ps -aq)
        
        - name: Docker Run 
          shell: docker run --name trcweb -dp 80:80 avsek12/trcweb

                 